### ISSUE TITLE
Missing data for Macbook1,1

### ISSUE THREAD

**Issue by finetuning-mg** [upekkha/AppleHardwareTest#31]
Hi,
thank you for this excellent repository of AHT info!
I would like to suggest to add a line about MacBook1,1 - AHT 3A104.
The file is here: http://download.info.apple.com/Apple_Hardware_Test/018-2393-A.dmg

I have just tested the file and it works fine with a USB stick on an old MacBook 13.3" (first series)

I would also suggest to point out in your readme that some old DMGs from Apple website have to be converted with Disk Utility before use (at least on High Sierra).

Many thanks and kind regards,
Mattia

**Comment by maslyankov** [comment]
I had success with this one on this (https://everymac.com/systems/apple/macbook/specs/macbook_2.0_white.html) model.
http://download.info.apple.com/Apple_Hardware_Test/018-2418-A.dmg

**Comment by upekkha** [comment]
Thanks for the input.

The readme now explains how to convert legacy images.  [4c46d6b628960353647005e81d749569ba6c6ce3]

I also added a reference to the Macbook1,1 for the "unidentified" AHT [8e69786c285f3bcd4ebbe37bd40d2477e7a95e10], but decided to keep it under 'Misc' instead of moving it to the 'Macbook' section. The reason is that I had, at some point, opened and checked all AHT and most contain a file inside with a reference to the corresponding hardware. The 'unidentified' did not contain such a mention (as far as I remember) and are therefore treated separately. Given that this dmg may also work with other models, I leave it under 'Misc'.
